# Generated by Django 4.2.9 on 2024-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
